# This is a workflow to build the UCSC Cell Browser docker image
#
# Docker modules are run on pull requests when code for files that affect the Docker image have changed.
# If other files are used during the Docker build, they should be added to `paths`
#

name: Build docker image for cellbrowser-scpca

concurrency:
  # only one run per branch at a time
  group: "docker_cellbrowser_${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - "docker/cellbrowser/Dockerfile"
      - "docker/cellbrowser/.dockerignore"
      - "docker/cellbrowser/pixi.lock"
  push:
    branches:
      - main
      - development
    paths:
      - "docker/cellbrowser/Dockerfile"
      - "docker/cellbrowser/.dockerignore"
      - "docker/cellbrowser/pixi.lock"

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: alexslemonade
  IMAGE_NAME: scpca-nf/cellbrowser

jobs:
  test-build:
    name: Test Build Docker Image
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker/cellbrowser"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-push:
    name: Build and Push Docker Image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=edge,branch=development
            type=ref,event=push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker/cellbrowser"
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
