name: Run Workflow on AWS Batch

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: Tagged workflow version to deploy (optional)
        required: false
      project:
        description: Project ID
        required: false
      run_ids:
        description: Comma-separated list of run IDs to process
        required: false
      run_mode:
        description: Nextflow workflow run mode
        type: choice
        options:
          - testing
          - example
          - staging
      celltyping:
        description: Perform celltyping analysis
        type: boolean
        default: true

      cnv_inference:
        description: Perform CNV inference
        type: boolean
        default: true
      resume:
        description: Use -resume flag for Nextflow launch
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Run Code Deploy Job
    runs-on: ubuntu-latest
    environment: "prod"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::997241705947:role/gha-nf-codedeploy-role
          role-session-name: githubActionSession
          aws-region: us-east-1

      - name: Create tmux launch script
        env:
          # use the provided version tag input or use to the current branch/ref name
          revision: ${{ inputs.version_tag || github.ref_name }}
          run_mode: ${{ inputs.run_mode }}
          project: ${{ inputs.project }}
          run_ids: ${{ inputs.run_ids }}
          celltyping: ${{ inputs.celltyping }}
          cnv_inference: ${{ inputs.cnv_inference }}
          resume: ${{ inputs.resume }}
        run: |
          echo "Using revision: $revision"

          # check that the version tag exists if it was specified
          if [ -z $(git tag -l "$revision") ] && [ "$revision" != "${{ github.ref_name }}" ]; then
            echo "Error: Specified version tag '${revision}' does not exist."
            exit 1
          fi

          # create job name from run mode and revision, transforming / and . to -
          job_name=${run_mode}_${revision//[\/.]/-}
          nextflow_params=""

          # append run_ids or project to nextflow params and job name
          if [ -n "$run_ids" ]; then
            nextflow_params="${nextflow_params} --run_ids $run_ids"
            # make a job name friendly version of run_ids and append to JOB_NAME
            job_name=${job_name}_${run_ids//,/-}
          elif [ -n "$project" ]; then
            nextflow_params="${nextflow_params} --project $project"
            job_name=${job_name}_${project//,/-}
          fi

          # append celltyping and cnv_inference flags if true
          # note that for profiles where these default to true, these flags are redundant (but harmless)
          # We don't support turning these off via GHA inputs at this time.
          if [ "$celltyping" = "true" ]; then
            nextflow_params="${nextflow_params} --perform_celltyping"
          fi
          if [ "$cnv_inference" = "true" ]; then
            nextflow_params="${nextflow_params} --perform_cnv_inference"
          fi

          # append GHA run and attempt to ensure uniqueness
          job_name=${job_name}_${{ github.run_id }}-${{ github.run_attempt }}

          cat > scripts/tmux_launch.sh <<TMUX_EOF
          #!/bin/bash
          export REVISION=$revision
          export RUN_MODE=$run_mode
          export JOB_NAME=$job_name
          export NEXTFLOW_PARAMS="${nextflow_params}"
          export RESUME=$resume
          tmux new-session -d -s nextflow /opt/nextflow/scripts/run_nextflow.sh
          TMUX_EOF

          chmod +x scripts/tmux_launch.sh

      - name: Create zip archive
        run: |
          mv scripts/aws/appspec.yml appspec.yml
          mv scripts/aws/run_nextflow.sh scripts/run_nextflow.sh
          zip -r source.zip . -i appspec.yml LICENSE scripts/tmux_launch.sh scripts/run_nextflow.sh
        working-directory: ${{ github.workspace }}

      - name: Copy zip to S3
        run: aws s3 cp source.zip s3://pipeline-artifacts-997241705947-us-east-1/
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Trigger AWS CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name Nextflow-batch \
            --deployment-group-name Nextflow-batch-deployment-group \
                  --s3-location bucket=pipeline-artifacts-997241705947-us-east-1,key=source.zip,bundleType=zip \
                  --region us-east-1
        env:
          AWS_DEFAULT_REGION: us-east-2
